
export const locations= [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
  { value: "AS", label: "American Samoa" },
  { value: "GU", label: "Guam" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "PR", label: "Puerto Rico" },
  { value: "VI", label: "Virgin Islands" },
];

export const fieldsOfStudy = [
  { value: "1", label: "Agriculture" },
  { value: "3", label: "Natural Resources and Conservation" },
  { value: "4", label: "Architecture and Related Services" },
  { value: "5", label: "Area, Ethnic, Cultural & Gender Studies" },
  { value: "9", label: "Communication, Journalism, and Related Programs" },
  { value: "10", label: "Communications Technologies/Technicians and Support Services" },
  { value: "11", label: "Computer and Information Sciences and Support Services" },
  { value: "12", label: "Personal and Culinary Services" },
  { value: "13", label: "Education" },
  { value: "14", label: "Engineering" },
  { value: "15", label: "Engineering Technologies and Engineering-Related Fields" },
  { value: "16", label: "Foreign Languages, Literatures, and Linguistics" },
  { value: "19", label: "Family and Consumer Sciences/Human Sciences" },
  { value: "22", label: "Legal Professions and Studies" },
  { value: "23", label: "English Language and Literature/Letters" },
  { value: "24", label: "Liberal Arts and Sciences" },
  { value: "25", label: "Library Science" },
  { value: "26", label: "Biological and Biomedical Sciences" },
  { value: "27", label: "Mathematics and Statistics" },
  { value: "29", label: "Military Technologies and Applied Sciences" },
  { value: "30", label: "Multidisciplinary/Interdisciplinary Studies" },
  { value: "31", label: "Parks, Recreaton & Liesure & Fitness Studies" },
  { value: "32", label: "Basic Skills" },
  { value: "33", label: "Citizenship Activities" },
  { value: "34", label: "Health-Related Knowledge and Skills" },
  { value: "35", label: "Interpersonal and Social Skills" },
  { value: "36", label: "Leisure and Recreational Activities" },
  { value: "37", label: "Personal Awareness and Self-Improvement" },
  { value: "38", label: "Philosophy and Religious Studies" },
  { value: "39", label: "Theology and Religious Vocations" },
  { value: "40", label: "Physical Sciences" },
  { value: "41", label: "Science Technologies/Technicians" },
  { value: "42", label: "Psychology" },
  { value: "43", label: "Homeland Security & Law Enforcement" },
  { value: "44", label: "Public Administration and Social Service Professions" },
  { value: "45", label: "Social Sciences" },
  { value: "46", label: "Construction Trades" },
  { value: "47", label: "Mechanic and Repair Technologies/Technicians" },
  { value: "48", label: "Precision Production" },
  { value: "49", label: "Transportation and Materials Moving" },
  { value: "50", label: "Visual and Performing Arts" },
  { value: "51", label: "Health Professions and Related Programs" },
  { value: "52", label: "Business, Management,Marketing & Related" },
  { value: "54", label: "History" },
  { value: "60", label: "Residency Programs" },
];

export const filterOptions = {
  locations,
  fieldsOfStudy,
};

export default filterOptions;